# ----
# Site

title: Clyde Great Glen Planniung
# url: "https://numbat70.github.io/edition-jekyll-template/search/?q=friends"
url: "https://numbat70.github.io/edition-jekyll-template/search/?q=friends"
baseurl: /greatglen
google_analytics_key: 
show_full_navigation: true

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /CLYDEfavicon.png
description: Clyde Great Glen
author:
  name:
  email:
  twitter: # twitter username without the @ symbol
social:
  name: Clyde Great Glen
  links:
    - https://github.com/numbat70/greatglen

# -----
# Build

timezone: Etc/UTC

permalink: pretty

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

collections:
  docs:
    title: Documentation
    permalink: /:path/
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: ""
      type: "docs"
    values:
      seo:
        type: Article
      _comments:
        category: Group navigation links with this field
        order: Used to sort links in the navigation
      _options:
        content:
          width: 800
          height: 2000
  -
    scope:
      path: ""
      type: "posts"
    values:
      _comments:
        type: Marks the impact of this release

# -----------
# CloudCannon

types:
  - minor
  - major
  - info
